sudo: false
language: node_js
node_js:
  - "5.1.1" # same as .node-version
before_install:
- node ./utils/quitIfFork.js
- npm install -g grunt-cli bower
install:
- travis_retry npm install
- bower install
before_script:
- bower install
- grunt connect:keepalive &
script:
- grunt
- grunt test:full
- grunt karma:minified
after_success:
- grunt coveralls
env:
  global:
  - secure: S6sdJYgRgdlwGR14hTH8zYSkF+bvjKiCEpsxHdiQLJL6T9hgByObdkpiOiKnt4Y2uuAfY0JUKsM/TG4apN22mH0R+xafmYx7+uMMEcBDB5EWJtohdaCkg/GgRFRTs5FkkJKBS+lIObDjjRyeGFh2uGjyXTTgtp+m1FIFj3mOQlw=
  - secure: jRx4ZPL0X0+LbAhPL9gYcTePHLtOhuiN2hamfbKCWL9ASvNhHTGeU4jZ/k2pDdaiNC2Hr4ZUglJPqGQ3VkrzKU9WJYg2/SpBpO/ERe39d2wE/qyx/AOYXMqzb07YGi2E4CnmAE5r0DIqMC+VIzPzqfz1mxKOq8bTcemT4z3xKkU=
notifications:
  email: false
  slack:
    secure: IyMKdUkXFeSPf0oTgHuvXGhJjJfiZTUbe/WUDyoOHgCuN/sempE0zHphwF/dEOcnGNsi7quGTTlv2AUq9ADVe4yeVy9YuxJqnNBeNMXViA+pBVX4A8W7UxaQclM+gWFteoK52EtjUNZNuZ5XOKFo04QtGxhaN4Qddd6geSR+fPE=
