language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower protractor
install: npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bower install
script: grunt
notifications:
  email: false
  hipchat:
    rooms:
      secure: fTJRrIZaHZnNEBCzLtPK638AJSiPa0pMAdzY3fgIGa4XFC4JaCRdGK4WSSTUo6tbxAGVWEmExIBozmiEyGl/YGPMREouHyaahY8U+u8twxhGFIUD5zmSNeVfcQn1z8GZAYDthLvfelSx9pjxh4wZ4pcF/hKBXwMYonTHiEcaEs0=
    template:
      - '%{repository}#%{build_number} (%{branch}): %{message} (<a href="%{build_url}">Details</a>)'
    format: html